

services:
  dbmanagerapi:
    image: ${DOCKER_REGISTRY-}dbmanagerapi
    build:
      context: .
      dockerfile: ./DbManagerApi/Dockerfile
    container_name: dbmanagerapi
    networks:
      - SpellCheckNetwork
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      mssql:
        condition: service_healthy
    volumes:
      - ~/Desktop:/app/desktop

    environment:
      ConnectionStrings__DefaultConnection: Server=sql2025,1433;Database=${MSSQL_DATABASE};User Id=${MSSQL_USER};Password=${MSSQL_USER_PASSWORD};TrustServerCertificate=True;
      JWT__Issuer: "DbManagerApi"
      JWT__Audience: "test.client.com"
      JWT__AccessTokenExpirationInSeconds: "3600"
      JWT__RefreshTokenExpirationInSeconds: "604800"
      JWT__SecretKey: ${JWT__SecretKey}
      JWT__ValidateIssuer: true
      JWT__ValidateLifetime: true
      JWT__ValidateIssuerSigningKey: true
      JWT__ValidateAudience: false

      APIAdministrator__RegisterAdministrator: true
      APIAdministrator__Email: ${APIAdministrator__Email}
      APIAdministrator__Password: ${APIAdministrator__Password}
      APIAdministrator__Username: APIAdministrator

      APIAdministrator__Client__RegisterTestClient: true
      APIAdministrator__Client__Id: ${APIAdministrator__Client__Id}
      APIAdministrator__Client__Name: ${APIAdministrator__Client__Name}
      APIAdministrator__Client__URL: ${APIAdministrator__Client__URL}
    env_file:
      - .env
  mssql:
    build:
      context: ./SqlServer/
      dockerfile: Dockerfile
    container_name: sql2025
    hostname: sql2025 
    # volumes:
    #   - ./scripts:/scripts
    env_file:
      - .env #by default. I specified though :D
    environment:
      MSSQL_DATABASE: ${MSSQL_DATABASE}
      MSSQL_USER: ${MSSQL_USER}
      MSSQL_USER_PASSWORD: ${MSSQL_USER_PASSWORD}

      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: "Developer"
    ports:
      - 1433:1433
    networks:
        - SpellCheckNetwork
    healthcheck:
      test: ["CMD", "/scripts/healthcheck.sh"]
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 15

networks:
  SpellCheckNetwork:
    driver: 
      bridge

