@DbManagerApi_HostAddress = https://localhost:7284

GET {{DbManagerApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{DbManagerApi_HostAddress}}/api/Users
Content-Type: application/json
{
  "Username" : "Opsik",
  "Password" : "1234",
  "Email" : "opsik@gmail.com"
  
}

###

GET {{DbManagerApi_HostAddress}}/api/Users
Authorization: Basic KzQ4MTIzMTIzMTIzOjEyMzQ=

###

DELETE {{DbManagerApi_HostAddress}}/api/users/1
Authorization: Basic KzQ4MTIzMTIzMTIzOjEyMzQ=

###

POST {{DbManagerApi_HostAddress}}/api/modules
Content-Type: application/json
Authorization: Basic KzQ4MTIzMTIzMTIzOjEyMzQ=
{
  "Name": "mod",
  "AuthorId": 2
}

###

# # # Authorization: Basic b3BzaWtAZ21haWwuY29tOjEyMzQ=

###

PUT {{DbManagerApi_HostAddress}}/api/modules/2
Content-Type: application/json
Authorization: Basic KzQ4MTIzMTIzMTIzOjEyMzQ=
{
  "Name":"mod2",
  "Words": [

  ]
}

###


GET {{DbManagerApi_HostAddress}}/api/Modules/2
Authorization: Basic KzQ4MTIzMTIzMTIzOjEyMzQ=

###
POST {{DbManagerApi_HostAddress}}/api/words
Content-Type: application/json
Authorization: Basic KzQ4MTIzMTIzMTIzOjEyMzQ=

{
    "AuthorId": 2,
    "ModuleId": 2,
    "Expression": "a",
    "Meaning": "",
    "DifficultyId": null
}

###
