name: .NET API CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: ${{ secrets.MSSQL_SA_PASSWORD }}
          ACCEPT_EULA: Y
        ports:
          - 1433:1433
        options: >-
          --health-cmd "exit 0"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    env:
      Solution_Name: SpellCheck.sln
      ConnectionStrings__DefaultConnection: "Server=localhost,1433;Database=TestDb;User Id=sa;Password=${{ secrets.MSSQL_SA_PASSWORD }};TrustServerCertificate=True"

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Wait for SQL Server
      run: |
        for i in {1..30}; do
          /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "${{ secrets.MSSQL_SA_PASSWORD }}" -Q "SELECT 1" && break
          echo "Waiting for SQL Server..."
          sleep 2
        done

    - name: Restore
      run: dotnet restore $Solution_Name

    - name: Build
      run: dotnet build $Solution_Name --configuration Release --no-restore

    - name: Install EF Core tools
      run: dotnet tool install --global dotnet-ef
    
    - name: Add .NET tools to PATH
      run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Apply EF Core migrations
      run: dotnet ef database update --project DbManagerApi/DbManagerApi.csproj

    - name: Run tests
      run: dotnet test $Solution_Name --configuration Release --no-build --logger "trx;LogFileName=test_results.trx" --results-directory ./TestResults

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./TestResults
